import type { Metadata } from "next"
// import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import Providers from "./providers/Providers"
import Navbar from "./components/Navbar"
// import PinterestSidebar from "./components/Sidebar"
import Label from "./components/Label"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
//${geistSans.variable} ${geistMono.variable}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Toaster />
        <Providers>
          <Navbar />
          {/* <PinterestSidebar /> */}

          <div className="mt-16">{children}</div>
          <div className="fixed top-4 right-4 z-50">
            <Label />
          </div>
        </Providers>
      </body>
    </html>
  )
}
